spring:
  data:
    mongodb:
      uri: 
      database: energy
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
